### ISSUE TITLE
Unicode error with python3

### ISSUE THREAD

**Issue by superSaen36** [toastdriven/itty#23]
I was running a script that imported itty and whenever I run it using python3 I get this error:
Traceback (most recent call last):
  File "connect_cisco_bot.py", line 1, in <module>
    from itty import post, run_itty
  File "/home/ubuntu/.local/lib/python3.5/site-packages/itty.py", line 588
    except UnicodeError, e:
                       ^
SyntaxError: invalid syntax

When I run it with python2.7 it works fine.

**Comment by frdante** [comment]
I'm getting the same issue using Python 3.7.3 in environment mode:

File "test.py", line 3, in <module>
    from itty import *
  File "/Users/yyy/Documents/projects/python/log/lib/python3.7/site-packages/itty.py", line 588
    except UnicodeError, e:
                       ^
SyntaxError: invalid syntax

**Comment by astrieanna** [comment]
I get the same issue using Python 3.9.9 on mac:

```
>>> from itty import get, run_itty
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/itty.py", line 588
    except UnicodeError, e:
                       ^
SyntaxError: invalid syntax
```

**Comment by astrieanna** [comment]
🤦🏻‍♀️  Ok, I found the correct repo for python3 support: https://github.com/toastdriven/itty3/

(Just leaving a breadcrumb here for anyone else who ends up here.)
