### ISSUE TITLE
Returning unicode strings as response causes wsgi error

### ISSUE THREAD

**Issue by justinabrahms** [toastdriven/itty#6]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.6.2/lib/python2.6/wsgiref/handlers.py", line 94, in run
    self.finish_response()
  File "/usr/local/Cellar/python/2.6.2/lib/python2.6/wsgiref/handlers.py", line 135, in finish_response
    self.write(data)
  File "/usr/local/Cellar/python/2.6.2/lib/python2.6/wsgiref/handlers.py", line 210, in write
    assert type(data) is StringType,"write() argument must be string"
AssertionError: write() argument must be string
localhost - - [11/Jan/2010 11:02:47] "GET / HTTP/1.1" 500 59

When returning string u'Test?\n'

**Comment by toastdriven** [comment]
I believe I have this fixed in SHA: 2a5ae6d5a7f9b18f9aca69d1085b05f41057b6f4. Thanks for pointing this out and very sorry.
